### ISSUE TITLE
how to handle the if length of the context exceeds max length (1024)

### ISSUE THREAD

**Issue by santhoshkolloju** [iedmrc/galois-autocompleter#1]
How can we handle if the length of the context is greater than 1024 which is max length of GPT-2

**Comment by iedmrc** [comment]
In GPT-2 you must just limit the input sequence to a fixed length. There is no such a clear way introduced in the original GPT-2 paper, as I understood. There is a **great** explanation of GPT-2 [here](https://jalammar.github.io/illustrated-gpt2/) by [jalammar](https://github.com/jalammar). 

At that point, **Transformer-XL** introduces new concepts called "Segment-level Recurrence" and "Relative Positional Encodings" . You can check the link [here](https://ai.googleblog.com/2019/01/transformer-xl-unleashing-potential-of.html) for more details.
