### ISSUE TITLE
you can add a score and ranking for the promotion 

### ISSUE THREAD

**Issue by 312shan** [iedmrc/galois-autocompleter#3]
You can add a score and ranking for the promotion like a this product
[tabNine](https://tabnine.com/blog/deep/)

**Comment by iedmrc** [comment]
Thanks for your interest.
My next intention is to make it work on personal computers, without needing a GPU. Microsoft actually released a similar code-completer for its vscode editor. I want it to be a code completer that works on many known editors, locally and freely.
But it's free and open-source, so you can fork and add these features you talk about as you want :).
