### ISSUE TITLE
About training .. 

### ISSUE THREAD

**Issue by dimwael** [iedmrc/galois-autocompleter#4]
When you specify the training directory to the model, did you extract all .py files and delete the other types or the model will parse all the projects directories that you cloned from Github one by one ?

**Comment by iedmrc** [comment]
The model has no such feature. It's data preprocessing and completely depends on you. It'll learn what you give it. This might be .py files as well as .c files and so on. But first, you must tokenize all the input files, before training. You can find details about those processes at https://github.com/minimaxir/gpt-2-simple repository or please refer to the original GPT-2 paper to have more information about the mathematics behind it.
And yes, I just have tokenized all .py files while throwing away others.
